"""Add question_type to LessonQuiz

Revision ID: 0f0193d8fd3e
Revises: 
Create Date: 2025-01-13 14:32:30.452877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0193d8fd3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               nullable=True)

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('lesson_quiz', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
